	var app = angular.module('myapp',['ui.router']);
		app.config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
			$urlRouterProvider.otherwise('/home');
			$stateProvider.state('homepage',{
				url:'/home',
				templateUrl:'view/homeView.html',
				controller:'homeController'
			}).state('detail',{
				url:'/detail/:id',
				templateUrl:'view/detail.html',
				controller:'detailController'
			}).state('program',{
				url:'/program',
				templateUrl:'view/program.html',
				controller:'programController'
			}).state('ring',{
				url:'/ring',
				templateUrl:'view/ring.html'
			}).state('login',{
				url:'/login',
				templateUrl:'view/login.html',
				controller:'loginController'
			}).state('personal',{
				url:'/personal',
				templateUrl:'view/personal.html',
				controller:'personalController'
			})
			.state('personal.per-1',{
				url:'/per-1',
				templateUrl:'view/per-1.html'
			}).state('personal.per-2',{
				url:'/per-2',
				templateUrl:'view/per-2.html'
			}).state('personal.per-3',{
				url:'/per-3',
				templateUrl:'view//per-3.html'
			}).state('personal.per-4',{
				url:'/per-4',
				templateUrl:'view//per-4.html'
			})
			.state('personal.per-5',{
				url:'/per-5',
				templateUrl:'view//per-5.html'
			})
			.state('password',{
				url:'/password',
				templateUrl:'view/password.html',
				controller:'passwordController'
			}).state('register',{
				url:'/register',
				templateUrl:'view/register.html',
				controller:'registerController'
			}).state('form',{
				url:'/form',
				templateUrl:'view/form.html',
				controller:'formController'
			}).state('form.form-1',{
				url:'/form-1',
				templateUrl:'view/form-1.html',
			}).state('form.form-2',{
				url:'/form-2',
				templateUrl:'view/form-2.html',
			}).state('form.form-3',{
				url:'/form-3',
				templateUrl:'view/form-3.html',
			})
		}]);